---
# handlers file for setup-apache
- name : service is starting httpd
  service :
     name : httpd
     state : started
  when : ansible_os_family=="RedHat"
- name : apache is starting
  service :
     name : apache2
     state : started
  when : ansible_os_family=="Debian"
- name : restart the httpd
  service :
     name : httpd
     state : restarted
  when : ansible_os_family=="RedHat"
- name : restart apache2
  service :
     name : apache2
     state : restarted
  when : ansible_os_family=="Debian"


